// Generated by Haxe 4.1.0-rc.1+cd0f0219b
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.io {
	public class BytesOutput : global::haxe.io.Output {
		
		public BytesOutput(global::haxe.lang.EmptyObject empty) : base(global::haxe.lang.EmptyObject.EMPTY) {
		}
		
		
		public BytesOutput() {
			#line 35 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
			global::haxe.io.BytesOutput.__hx_ctor_haxe_io_BytesOutput(this);
		}
		#line default
		
		protected static void __hx_ctor_haxe_io_BytesOutput(global::haxe.io.BytesOutput __hx_this) {
			#line 40 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
			__hx_this.b = new global::haxe.io.BytesBuffer();
		}
		#line default
		
		public global::haxe.io.BytesBuffer b;
		
		
		
		public int get_length() {
			unchecked {
				#line 48 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
				long x = ( this.b.b as global::System.IO.Stream ).Length;
				#line 48 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
				if (( ((bool) (( ((long) (x) ) < -2147483648 )) ) || ((bool) (( ((long) (x) ) > 2147483647 )) ) )) {
					#line 48 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
					throw global::haxe.lang.HaxeException.wrap("Overflow");
				}
				
				#line 48 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
				return ((int) (((long) (x) )) );
			}
			#line default
		}
		
		
		public override void writeByte(int c) {
			#line 55 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
			( this.b.b as global::System.IO.Stream ).WriteByte(((byte) (c) ));
		}
		#line default
		
		public override int writeBytes(global::haxe.io.Bytes buf, int pos, int len) {
			#line 65 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
			{
				#line 65 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
				global::haxe.io.BytesBuffer _this = this.b;
				#line 65 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
				if (( ( ( pos < 0 ) || ( len < 0 ) ) || ( ( pos + len ) > buf.length ) )) {
					#line 65 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
					throw global::haxe.lang.HaxeException.wrap(global::haxe.io.Error.OutsideBounds);
				}
				
				#line 65 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
				( _this.b as global::System.IO.Stream ).Write(((byte[]) (buf.b) ), ((int) (pos) ), ((int) (len) ));
			}
			
			#line 67 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
			return len;
		}
		#line default
		
		public virtual global::haxe.io.Bytes getBytes() {
			#line 143 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
			return this.b.getBytes();
		}
		#line default
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
				switch (hash) {
					case 98:
					{
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						this.b = ((global::haxe.io.BytesBuffer) (@value) );
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						return @value;
					}
					
					
					default:
					{
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
				switch (hash) {
					case 493819893:
					{
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "getBytes", 493819893)) );
					}
					
					
					case 1381630732:
					{
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "writeBytes", 1381630732)) );
					}
					
					
					case 1238832007:
					{
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "writeByte", 1238832007)) );
					}
					
					
					case 261031087:
					{
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_length", 261031087)) );
					}
					
					
					case 520590566:
					{
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						return this.get_length();
					}
					
					
					case 98:
					{
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						return this.b;
					}
					
					
					default:
					{
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
				switch (hash) {
					case 520590566:
					{
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						return ((double) (this.get_length()) );
					}
					
					
					default:
					{
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
				switch (hash) {
					case 1238832007:
					case 1381630732:
					{
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						return global::haxe.lang.Runtime.slowCallField(this, field, dynargs);
					}
					
					
					case 493819893:
					{
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						return this.getBytes();
					}
					
					
					case 261031087:
					{
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						return this.get_length();
					}
					
					
					default:
					{
						#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::haxe.root.Array baseArr) {
			#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
			baseArr.push("length");
			#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
			baseArr.push("b");
			#line 25 "C:\\HaxeToolkit\\haxe\\std\\haxe\\io\\BytesOutput.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}


