// Generated by Haxe 4.1.0-rc.1+0d88c583b
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace web {
	public class GameSetting : global::haxe.lang.HxObject {
		
		public GameSetting(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public GameSetting() {
			#line 7 "d:\\project\\sangong\\sangong\\src\\web\\GameSetting.hx"
			global::web.GameSetting.__hx_ctor_web_GameSetting(this);
		}
		#line default
		
		protected static void __hx_ctor_web_GameSetting(global::web.GameSetting __hx_this) {
		}
		
		
		public static bool getInstallGame(uint id) {
			#line 14 "d:\\project\\sangong\\sangong\\src\\web\\GameSetting.hx"
			return true;
		}
		#line default
		
		public static void InstallGame(uint id, string name) {
		}
		
		
	}
}


