// Generated by Haxe 4.1.0-rc.1+0d88c583b

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace web {
	public struct TinyCMDCS {
		
		
		
		public object cmd;
		
		public object @value;
		
		public object id;
		
		public object password;
		
		public string openid;
		
		public object[] players;
		
		public object player;
		
	}
}


