// Generated by Haxe 4.1.0-rc.1+0d88c583b
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.root {
	public class Lambda : global::haxe.lang.HxObject {
		
		public Lambda(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Lambda() {
			global::haxe.root.Lambda.__hx_ctor__Lambda(this);
		}
		
		
		protected static void __hx_ctor__Lambda(global::haxe.root.Lambda __hx_this) {
		}
		
		
		public static global::haxe.root.Array array(object it) {
			global::haxe.root.Array a = new global::haxe.root.Array();
			{
				object i = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(i, "hasNext", 407283053, null))) {
					object i1 = ((object) (global::haxe.lang.Runtime.callField(i, "next", 1224901875, null)) );
					a.push(i1);
				}
				
			}
			
			return a;
		}
		
		
		public static global::haxe.ds.List list(object it) {
			global::haxe.ds.List l = new global::haxe.ds.List();
			{
				object i = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(i, "hasNext", 407283053, null))) {
					object i1 = ((object) (global::haxe.lang.Runtime.callField(i, "next", 1224901875, null)) );
					l.@add(i1);
				}
				
			}
			
			return l;
		}
		
		
		public static global::haxe.root.Array map(object it, global::haxe.lang.Function f) {
			global::haxe.root.Array _g = new global::haxe.root.Array(new object[]{});
			{
				object x = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(x, "hasNext", 407283053, null))) {
					object x1 = ((object) (global::haxe.lang.Runtime.callField(x, "next", 1224901875, null)) );
					_g.push(((object) (f.__hx_invoke1_o(default(double), x1)) ));
				}
				
			}
			
			return _g;
		}
		
		
		public static global::haxe.root.Array mapi(object it, global::haxe.lang.Function f) {
			int i = 0;
			global::haxe.root.Array _g = new global::haxe.root.Array(new object[]{});
			{
				object x = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(x, "hasNext", 407283053, null))) {
					object x1 = ((object) (global::haxe.lang.Runtime.callField(x, "next", 1224901875, null)) );
					_g.push(((object) (f.__hx_invoke2_o(((double) (i++) ), global::haxe.lang.Runtime.undefined, default(double), x1)) ));
				}
				
			}
			
			return _g;
		}
		
		
		public static global::haxe.root.Array flatten(object it) {
			global::haxe.root.Array _g = new global::haxe.root.Array(new object[]{});
			{
				object e = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(e, "hasNext", 407283053, null))) {
					object e1 = ((object) (global::haxe.lang.Runtime.callField(e, "next", 1224901875, null)) );
					{
						object x = ((object) (global::haxe.lang.Runtime.callField(e1, "iterator", 328878574, null)) );
						while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(x, "hasNext", 407283053, null))) {
							object x1 = ((object) (global::haxe.lang.Runtime.callField(x, "next", 1224901875, null)) );
							_g.push(x1);
						}
						
					}
					
				}
				
			}
			
			return _g;
		}
		
		
		public static global::haxe.root.Array flatMap(object it, global::haxe.lang.Function f) {
			global::haxe.root.Array _g = new global::haxe.root.Array(new object[]{});
			{
				object x = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(x, "hasNext", 407283053, null))) {
					object x1 = ((object) (global::haxe.lang.Runtime.callField(x, "next", 1224901875, null)) );
					_g.push(((object) (f.__hx_invoke1_o(default(double), x1)) ));
				}
				
			}
			
			global::haxe.root.Array _g1 = new global::haxe.root.Array(new object[]{});
			{
				object e = ((object) (global::haxe.lang.Runtime.callField(((object) (_g) ), "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(e, "hasNext", 407283053, null))) {
					object e1 = ((object) (global::haxe.lang.Runtime.callField(e, "next", 1224901875, null)) );
					{
						object x2 = ((object) (global::haxe.lang.Runtime.callField(e1, "iterator", 328878574, null)) );
						while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(x2, "hasNext", 407283053, null))) {
							object x3 = ((object) (global::haxe.lang.Runtime.callField(x2, "next", 1224901875, null)) );
							_g1.push(x3);
						}
						
					}
					
				}
				
			}
			
			return _g1;
		}
		
		
		public static bool has(object it, object elt) {
			{
				object x = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(x, "hasNext", 407283053, null))) {
					object x1 = ((object) (global::haxe.lang.Runtime.callField(x, "next", 1224901875, null)) );
					if (global::haxe.lang.Runtime.eq(x1, elt)) {
						return true;
					}
					
				}
				
			}
			
			return false;
		}
		
		
		public static bool exists(object it, global::haxe.lang.Function f) {
			{
				object x = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(x, "hasNext", 407283053, null))) {
					object x1 = ((object) (global::haxe.lang.Runtime.callField(x, "next", 1224901875, null)) );
					if (global::haxe.lang.Runtime.toBool(f.__hx_invoke1_o(default(double), x1))) {
						return true;
					}
					
				}
				
			}
			
			return false;
		}
		
		
		public static bool @foreach(object it, global::haxe.lang.Function f) {
			{
				object x = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(x, "hasNext", 407283053, null))) {
					object x1 = ((object) (global::haxe.lang.Runtime.callField(x, "next", 1224901875, null)) );
					if ( ! (global::haxe.lang.Runtime.toBool(f.__hx_invoke1_o(default(double), x1))) ) {
						return false;
					}
					
				}
				
			}
			
			return true;
		}
		
		
		public static void iter(object it, global::haxe.lang.Function f) {
			object x = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
			while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(x, "hasNext", 407283053, null))) {
				object x1 = ((object) (global::haxe.lang.Runtime.callField(x, "next", 1224901875, null)) );
				f.__hx_invoke1_o(default(double), x1);
			}
			
		}
		
		
		public static global::haxe.root.Array filter(object it, global::haxe.lang.Function f) {
			global::haxe.root.Array _g = new global::haxe.root.Array(new object[]{});
			{
				object x = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(x, "hasNext", 407283053, null))) {
					object x1 = ((object) (global::haxe.lang.Runtime.callField(x, "next", 1224901875, null)) );
					if (global::haxe.lang.Runtime.toBool(f.__hx_invoke1_o(default(double), x1))) {
						_g.push(x1);
					}
					
				}
				
			}
			
			return _g;
		}
		
		
		public static object fold(object it, global::haxe.lang.Function f, object first) {
			{
				object x = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(x, "hasNext", 407283053, null))) {
					object x1 = ((object) (global::haxe.lang.Runtime.callField(x, "next", 1224901875, null)) );
					first = ((object) (f.__hx_invoke2_o(default(double), x1, default(double), first)) );
				}
				
			}
			
			return first;
		}
		
		
		public static int count(object it, global::haxe.lang.Function pred) {
			int n = 0;
			if (( pred == null )) {
				object _ = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(_, "hasNext", 407283053, null))) {
					object _1 = ((object) (global::haxe.lang.Runtime.callField(_, "next", 1224901875, null)) );
					 ++ n;
				}
				
			}
			else {
				object x = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(x, "hasNext", 407283053, null))) {
					object x1 = ((object) (global::haxe.lang.Runtime.callField(x, "next", 1224901875, null)) );
					if (global::haxe.lang.Runtime.toBool(((global::haxe.lang.Function) (pred) ).__hx_invoke1_o(default(double), x1))) {
						 ++ n;
					}
					
				}
				
			}
			
			return n;
		}
		
		
		public static bool empty(object it) {
			return  ! (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) ), "hasNext", 407283053, null))) ;
		}
		
		
		public static int indexOf(object it, object v) {
			unchecked {
				int i = 0;
				{
					object v2 = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
					while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(v2, "hasNext", 407283053, null))) {
						object v21 = ((object) (global::haxe.lang.Runtime.callField(v2, "next", 1224901875, null)) );
						if (global::haxe.lang.Runtime.eq(v, v21)) {
							return i;
						}
						
						 ++ i;
					}
					
				}
				
				return -1;
			}
		}
		
		
		public static object find(object it, global::haxe.lang.Function f) {
			{
				object v = ((object) (global::haxe.lang.Runtime.callField(it, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(v, "hasNext", 407283053, null))) {
					object v1 = ((object) (global::haxe.lang.Runtime.callField(v, "next", 1224901875, null)) );
					if (global::haxe.lang.Runtime.toBool(f.__hx_invoke1_o(default(double), v1))) {
						return v1;
					}
					
				}
				
			}
			
			return null;
		}
		
		
		public static global::haxe.root.Array concat(object a, object b) {
			global::haxe.root.Array l = new global::haxe.root.Array();
			{
				object x = ((object) (global::haxe.lang.Runtime.callField(a, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(x, "hasNext", 407283053, null))) {
					object x1 = ((object) (global::haxe.lang.Runtime.callField(x, "next", 1224901875, null)) );
					l.push(x1);
				}
				
			}
			
			{
				object x2 = ((object) (global::haxe.lang.Runtime.callField(b, "iterator", 328878574, null)) );
				while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(x2, "hasNext", 407283053, null))) {
					object x3 = ((object) (global::haxe.lang.Runtime.callField(x2, "next", 1224901875, null)) );
					l.push(x3);
				}
				
			}
			
			return l;
		}
		
		
	}
}


