// Generated by Haxe 4.1.0-rc.1+0d88c583b
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace sys {
	public class FileSystem : global::haxe.lang.HxObject {
		
		public FileSystem(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public FileSystem() {
			global::sys.FileSystem.__hx_ctor_sys_FileSystem(this);
		}
		
		
		protected static void __hx_ctor_sys_FileSystem(global::sys.FileSystem __hx_this) {
		}
		
		
		public static bool exists(string path) {
			if ( ! (global::System.IO.File.Exists(((string) (path) ))) ) {
				return global::System.IO.Directory.Exists(((string) (path) ));
			}
			else {
				return true;
			}
			
		}
		
		
		public static void rename(string path, string newPath) {
			global::System.IO.Directory.Move(((string) (path) ), ((string) (newPath) ));
		}
		
		
		public static object stat(string path) {
			if (global::System.IO.File.Exists(((string) (path) ))) {
				global::System.IO.FileInfo fi = new global::System.IO.FileInfo(path);
				global::haxe.root.Date tmp = new global::haxe.root.Date(((global::System.DateTime) (( fi as global::System.IO.FileSystemInfo ).LastAccessTime) ));
				global::haxe.root.Date tmp1 = new global::haxe.root.Date(((global::System.DateTime) (( fi as global::System.IO.FileSystemInfo ).LastWriteTime) ));
				global::haxe.root.Date tmp2 = new global::haxe.root.Date(((global::System.DateTime) (( fi as global::System.IO.FileSystemInfo ).CreationTime) ));
				{
					int __temp_odecl1 = ((int) (fi.Length) );
					return new global::haxe.lang.DynamicObject(new int[]{262801146, 651890926, 1302870512}, new object[]{tmp1, tmp, tmp2}, new int[]{4995541, 5145602, 5246186, 5841808, 499574632, 1214305123, 1269206179, 1280549057}, new double[]{((double) (0) ), ((double) (0) ), ((double) (0) ), ((double) (0) ), ((double) (0) ), ((double) (0) ), ((double) (0) ), ((double) (__temp_odecl1) )});
				}
				
			}
			else if (global::System.IO.Directory.Exists(((string) (path) ))) {
				global::System.IO.DirectoryInfo fi1 = new global::System.IO.DirectoryInfo(path);
				global::haxe.root.Date tmp3 = new global::haxe.root.Date(((global::System.DateTime) (( fi1 as global::System.IO.FileSystemInfo ).LastAccessTime) ));
				global::haxe.root.Date tmp4 = new global::haxe.root.Date(((global::System.DateTime) (( fi1 as global::System.IO.FileSystemInfo ).LastWriteTime) ));
				{
					global::haxe.root.Date __temp_odecl2 = new global::haxe.root.Date(((global::System.DateTime) (( fi1 as global::System.IO.FileSystemInfo ).CreationTime) ));
					return new global::haxe.lang.DynamicObject(new int[]{262801146, 651890926, 1302870512}, new object[]{tmp4, tmp3, __temp_odecl2}, new int[]{4995541, 5145602, 5246186, 5841808, 499574632, 1214305123, 1269206179, 1280549057}, new double[]{((double) (0) ), ((double) (0) ), ((double) (0) ), ((double) (0) ), ((double) (0) ), ((double) (0) ), ((double) (0) ), ((double) (0) )});
				}
				
			}
			else {
				throw global::haxe.lang.HaxeException.wrap(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Path \'", path), "\' doesn\'t exist"));
			}
			
		}
		
		
		public static string fullPath(string relPath) {
			return ( new global::System.IO.FileInfo(relPath) as global::System.IO.FileSystemInfo ).FullName;
		}
		
		
		public static string absolutePath(string relPath) {
			if (global::haxe.io.Path.isAbsolute(relPath)) {
				return relPath;
			}
			
			return global::haxe.io.Path.@join(new global::haxe.root.Array(new object[]{global::System.IO.Directory.GetCurrentDirectory(), relPath}));
		}
		
		
		public static bool isDirectory(string path) {
			bool isdir = global::System.IO.Directory.Exists(((string) (path) ));
			if (( isdir != global::System.IO.File.Exists(((string) (path) )) )) {
				return isdir;
			}
			
			throw global::haxe.lang.HaxeException.wrap(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Path \'", path), "\' doesn\'t exist"));
		}
		
		
		public static void createDirectory(string path) {
			global::System.IO.Directory.CreateDirectory(((string) (path) ));
		}
		
		
		public static void deleteFile(string path) {
			if ( ! (global::System.IO.File.Exists(((string) (path) ))) ) {
				throw global::haxe.lang.HaxeException.wrap(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Path \'", path), "\' doesn\'t exist"));
			}
			
			global::System.IO.File.Delete(((string) (path) ));
		}
		
		
		public static void deleteDirectory(string path) {
			if ( ! (global::System.IO.Directory.Exists(((string) (path) ))) ) {
				throw global::haxe.lang.HaxeException.wrap(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Path \'", path), "\' doesn\'t exist"));
			}
			
			global::System.IO.Directory.Delete(((string) (path) ));
		}
		
		
		public static global::haxe.root.Array readDirectory(string path) {
			unchecked {
				string[] ret = global::System.IO.Directory.GetFileSystemEntries(((string) (path) ));
				if (( ( ret as global::System.Array ).Length > 0 )) {
					string fst = ((string) (ret[0]) );
					string sep = "/";
					if (( global::haxe.lang.StringExt.lastIndexOf(fst, sep, null) < global::haxe.lang.StringExt.lastIndexOf(fst, "\\", null) )) {
						sep = "\\";
					}
					
					{
						int _g = 0;
						int _g1 = ( ret as global::System.Array ).Length;
						while (( _g < _g1 )) {
							int i = _g++;
							string path1 = ((string) (ret[i]) );
							ret[i] = global::haxe.lang.StringExt.substr(path1, ( global::haxe.lang.StringExt.lastIndexOf(path1, sep, null) + 1 ), null);
						}
						
					}
					
				}
				
				object[] ret1 = new object[( ret as global::System.Array ).Length];
				{
					int _g2 = 0;
					int _g11 = ( ret as global::System.Array ).Length;
					while (( _g2 < _g11 )) {
						int i1 = _g2++;
						ret1[i1] = ((string) (ret[i1]) );
					}
					
				}
				
				object[] dyn = ret1;
				return new global::haxe.root.Array(((object[]) (dyn) ));
			}
		}
		
		
	}
}


