// Generated by Haxe 4.0.2+606b176a3

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.ds._Map {
	public sealed class Map_Impl_ {
		
		public static void @set(global::haxe.IMap this1, object key, object @value) {
			#line 75 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			this1.@set(key, @value);
		}
		#line default
		
		public static object @get(global::haxe.IMap this1, object key) {
			#line 93 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			return this1.@get(key);
		}
		#line default
		
		public static bool exists(global::haxe.IMap this1, object key) {
			#line 101 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			return this1.exists(key);
		}
		#line default
		
		public static bool @remove(global::haxe.IMap this1, object key) {
			#line 110 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			return this1.@remove(key);
		}
		#line default
		
		public static object keys(global::haxe.IMap this1) {
			#line 118 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			return this1.keys();
		}
		#line default
		
		public static object iterator(global::haxe.IMap this1) {
			#line 127 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			return this1.iterator();
		}
		#line default
		
		public static object keyValueIterator(global::haxe.IMap this1) {
			#line 136 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			return this1.keyValueIterator();
		}
		#line default
		
		public static global::haxe.IMap copy(global::haxe.IMap this1) {
			#line 145 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			return ((global::haxe.IMap) (this1.copy()) );
		}
		#line default
		
		public static string toString(global::haxe.IMap this1) {
			#line 154 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			return this1.toString();
		}
		#line default
		
		public static void clear(global::haxe.IMap this1) {
			#line 161 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			this1.clear();
		}
		#line default
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public static object arrayWrite(global::haxe.IMap this1, object k, object v) {
			#line 165 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			this1.@set(k, v);
			return v;
		}
		#line default
		
		public static global::haxe.ds.StringMap toStringMap(global::haxe.IMap t) {
			#line 170 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			return new global::haxe.ds.StringMap();
		}
		#line default
		
		public static global::haxe.ds.IntMap toIntMap(global::haxe.IMap t) {
			#line 174 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			return new global::haxe.ds.IntMap();
		}
		#line default
		
		public static global::haxe.ds.EnumValueMap toEnumValueMapMap(global::haxe.IMap t) {
			#line 178 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			return new global::haxe.ds.EnumValueMap();
		}
		#line default
		
		public static global::haxe.ds.ObjectMap toObjectMap(global::haxe.IMap t) {
			#line 182 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			return new global::haxe.ds.ObjectMap();
		}
		#line default
		
		public static global::haxe.ds.StringMap fromStringMap(global::haxe.ds.StringMap map) {
			#line 186 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			return ((global::haxe.ds.StringMap) (map) );
		}
		#line default
		
		public static global::haxe.ds.IntMap fromIntMap(global::haxe.ds.IntMap map) {
			#line 190 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			return ((global::haxe.ds.IntMap) (map) );
		}
		#line default
		
		public static global::haxe.ds.ObjectMap fromObjectMap(global::haxe.ds.ObjectMap map) {
			#line 194 "C:\\HaxeToolkit\\haxe\\std\\haxe\\ds\\Map.hx"
			return ((global::haxe.ds.ObjectMap) (map) );
		}
		#line default
		
	}
}


