// Generated by Haxe 4.0.0+ef18b627e
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace server {
	public interface IHander : global::haxe.lang.IHxObject {
		
		void close();
		
		void send(global::haxe.io.Bytes data);
		
	}
}


