// Generated by Haxe 4.1.0-rc.1+0d88c583b
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.crypto.mode {
	public class CBC : global::haxe.lang.HxObject {
		
		public CBC(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public CBC() {
			global::haxe.crypto.mode.CBC.__hx_ctor_haxe_crypto_mode_CBC(this);
		}
		
		
		protected static void __hx_ctor_haxe_crypto_mode_CBC(global::haxe.crypto.mode.CBC __hx_this) {
		}
		
		
		public static void encrypt(global::haxe.io.Bytes src, global::haxe.io.Bytes iv, int blockSize, global::haxe.lang.Function encryptBlock) {
			global::haxe.io.Bytes vector = iv.sub(0, iv.length);
			int i = 0;
			int len = src.length;
			while (( i < len )) {
				{
					int _g = 0;
					int _g1 = blockSize;
					while (( _g < _g1 )) {
						int j = _g++;
						src.b[( i + j )] = ((byte) (( ((int) (((byte) (src.b[( i + j )]) )) ) ^ ((int) (((byte) (vector.b[j]) )) ) )) );
					}
					
				}
				
				encryptBlock.__hx_invoke4_o(default(double), src, ((double) (i) ), global::haxe.lang.Runtime.undefined, default(double), src, ((double) (i) ), global::haxe.lang.Runtime.undefined);
				vector = src.sub(i, blockSize);
				i += blockSize;
			}
			
		}
		
		
		public static void decrypt(global::haxe.io.Bytes src, global::haxe.io.Bytes iv, int blockSize, global::haxe.lang.Function decryptBlock) {
			int vpos = ( src.length - blockSize );
			int i = src.length;
			while (( i > 0 )) {
				i -= blockSize;
				vpos -= blockSize;
				decryptBlock.__hx_invoke4_o(default(double), src, ((double) (i) ), global::haxe.lang.Runtime.undefined, default(double), src, ((double) (i) ), global::haxe.lang.Runtime.undefined);
				if (( vpos < 0 )) {
					int _g = 0;
					int _g1 = blockSize;
					while (( _g < _g1 )) {
						int j = _g++;
						src.b[j] = ((byte) (( ((int) (((byte) (src.b[j]) )) ) ^ ((int) (((byte) (iv.b[j]) )) ) )) );
					}
					
				}
				else {
					int _g2 = 0;
					int _g11 = blockSize;
					while (( _g2 < _g11 )) {
						int j1 = _g2++;
						src.b[( i + j1 )] = ((byte) (( ((int) (((byte) (src.b[( i + j1 )]) )) ) ^ ((int) (((byte) (src.b[( vpos + j1 )]) )) ) )) );
					}
					
				}
				
			}
			
		}
		
		
	}
}


