// Generated by Haxe 4.1.0-rc.1+cd0f0219b
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.crypto.mode {
	public class PCBC : global::haxe.lang.HxObject {
		
		public PCBC(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public PCBC() {
			#line 5 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
			global::haxe.crypto.mode.PCBC.__hx_ctor_haxe_crypto_mode_PCBC(this);
		}
		#line default
		
		protected static void __hx_ctor_haxe_crypto_mode_PCBC(global::haxe.crypto.mode.PCBC __hx_this) {
		}
		
		
		public static void encrypt(global::haxe.io.Bytes src, global::haxe.io.Bytes iv, int blockSize, global::haxe.lang.Function encryptBlock) {
			#line 9 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
			global::haxe.io.Bytes vector = iv.sub(0, iv.length);
			int i = 0;
			#line 11 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
			int len = src.length;
			while (( i < len )) {
				#line 14 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
				global::haxe.io.Bytes plainText = src.sub(i, blockSize);
				{
					#line 15 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
					int _g = 0;
					#line 15 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
					int _g1 = blockSize;
					#line 15 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
					while (( _g < _g1 )) {
						#line 15 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
						int j = _g++;
						#line 17 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
						src.b[( i + j )] = ((byte) (( ((int) (((byte) (src.b[( i + j )]) )) ) ^ ((int) (((byte) (vector.b[j]) )) ) )) );
					}
					
				}
				
				#line 20 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
				encryptBlock.__hx_invoke4_o(default(double), src, ((double) (i) ), global::haxe.lang.Runtime.undefined, default(double), src, ((double) (i) ), global::haxe.lang.Runtime.undefined);
				vector = src.sub(i, blockSize);
				#line 22 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
				{
					#line 22 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
					int _g2 = 0;
					#line 22 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
					int _g3 = blockSize;
					#line 22 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
					while (( _g2 < _g3 )) {
						#line 22 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
						int j1 = _g2++;
						#line 24 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
						vector.b[j1] = ((byte) (( ((int) (((byte) (vector.b[j1]) )) ) ^ ((int) (((byte) (plainText.b[j1]) )) ) )) );
					}
					
				}
				
				#line 26 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
				i += blockSize;
			}
			
		}
		#line default
		
		public static void decrypt(global::haxe.io.Bytes src, global::haxe.io.Bytes iv, int blockSize, global::haxe.lang.Function decryptBlock) {
			#line 32 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
			global::haxe.io.Bytes vector = iv.sub(0, iv.length);
			int i = 0;
			#line 34 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
			int len = src.length;
			while (( i < len )) {
				#line 37 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
				global::haxe.io.Bytes cipherText = src.sub(i, blockSize);
				decryptBlock.__hx_invoke4_o(default(double), src, ((double) (i) ), global::haxe.lang.Runtime.undefined, default(double), src, ((double) (i) ), global::haxe.lang.Runtime.undefined);
				#line 39 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
				{
					#line 39 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
					int _g = 0;
					#line 39 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
					int _g1 = blockSize;
					#line 39 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
					while (( _g < _g1 )) {
						#line 39 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
						int j = _g++;
						src.b[( i + j )] = ((byte) (( ((int) (((byte) (src.b[( i + j )]) )) ) ^ ((int) (((byte) (vector.b[j]) )) ) )) );
					}
					
				}
				
				#line 41 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
				vector = src.sub(i, blockSize);
				{
					#line 42 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
					int _g2 = 0;
					#line 42 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
					int _g3 = blockSize;
					#line 42 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
					while (( _g2 < _g3 )) {
						#line 42 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
						int j1 = _g2++;
						#line 44 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
						vector.b[j1] = ((byte) (( ((int) (((byte) (vector.b[j1]) )) ) ^ ((int) (((byte) (cipherText.b[j1]) )) ) )) );
					}
					
				}
				
				#line 46 "C:\\HaxeToolkit\\haxe\\lib\\crypto\\0,3,0\\src\\haxe\\crypto\\mode\\PCBC.hx"
				i += blockSize;
			}
			
		}
		#line default
		
	}
}


