// Generated by Haxe 4.1.0-rc.1+0d88c583b
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace binary128.@internal.cs {
	public class Leb128 : global::haxe.lang.HxObject {
		
		public Leb128(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Leb128() {
			global::binary128.@internal.cs.Leb128.__hx_ctor_binary128_internal_cs_Leb128(this);
		}
		
		
		protected static void __hx_ctor_binary128_internal_cs_Leb128(global::binary128.@internal.cs.Leb128 __hx_this) {
		}
		
		
		public static void writeSigned64LEB128(global::haxe.io.BytesOutput buf, long @value) {
			unchecked {
				bool more = false;
				while (true) {
					long bt = ((long) (( @value & 127 )) );
					@value = ((long) (( @value >> 7 )) );
					more =  ! ((( ( ( @value == 0 ) && ( (((long) (( bt & 64 )) )) == 0 ) ) || ( ( @value == -1 ) && ( (((long) (( bt & 64 )) )) != 0 ) ) ))) ;
					if (more) {
						bt = ((long) (( bt | 128 )) );
					}
					
					buf.writeByte(((int) (bt) ));
					if ( ! (more) ) {
						break;
					}
					
				}
				
			}
		}
		
		
		public static void writeSigned32LEB128(global::haxe.io.BytesOutput buf, int @value) {
			unchecked {
				bool more = false;
				while (true) {
					int bt = ((int) (( @value & 127 )) );
					@value = ((int) (( @value >> 7 )) );
					more =  ! ((( ( ((bool) (( @value == 0 )) ) && ((bool) (( (((int) (( bt & 64 )) )) == 0 )) ) ) || ( ((bool) (( @value == -1 )) ) && ((bool) (( (((int) (( bt & 64 )) )) != 0 )) ) ) ))) ;
					if (more) {
						bt = ((int) (( bt | 128 )) );
					}
					
					buf.writeByte(((int) (bt) ));
					if ( ! (more) ) {
						break;
					}
					
				}
				
			}
		}
		
		
		public static void writeUnsigned64LEB128(global::haxe.io.BytesOutput buf, ulong @value) {
			unchecked {
				while (true) {
					ulong bt = ((ulong) (( @value & 127 )) );
					@value = ((ulong) (( @value >> 7 )) );
					if (( @value != 0 )) {
						bt = ((ulong) (( bt | 128 )) );
					}
					
					buf.writeByte(((int) (bt) ));
					if ( ! ((( @value != 0 ))) ) {
						break;
					}
					
				}
				
			}
		}
		
		
		public static void writeUnsigned32LEB128(global::haxe.io.BytesOutput buf, uint @value) {
			unchecked {
				while (true) {
					uint bt = ((uint) (( @value & 127 )) );
					@value = ((uint) (((uint) (( ((uint) (@value) ) >> 7 )) )) );
					if (((bool) (( @value != 0 )) )) {
						bt = ((uint) (( bt | 128 )) );
					}
					
					buf.writeByte(((int) (bt) ));
					if ( ! ((((bool) (( @value != 0 )) ))) ) {
						break;
					}
					
				}
				
			}
		}
		
		
		public static uint readSignedLEB128(global::haxe.io.BytesInput buf) {
			unchecked {
				int bt = 0;
				uint @value = ((uint) (0) );
				int shift = 0;
				while (true) {
					int ibt = buf.readByte();
					if (( ibt < 0 )) {
						throw global::haxe.lang.HaxeException.wrap("LEB128.ReadSLEB128(premature stream end)");
					}
					
					bt = ibt;
					@value = ((uint) (( @value | ( (( bt & 127 )) << shift ) )) );
					shift += 7;
					if ( ! ((( bt >= 128 ))) ) {
						break;
					}
					
				}
				
				if (( (( bt & 64 )) != 0 )) {
					@value = ((uint) (( @value | ( -1L << shift ) )) );
				}
				
				return @value;
			}
		}
		
		
		public static int readUnsignedLEB128(global::haxe.io.BytesInput buf) {
			unchecked {
				int @value = 0;
				int shift = 0;
				while (true) {
					int bt = buf.readByte();
					if (( bt < 0 )) {
						throw global::haxe.lang.HaxeException.wrap("LEB128.ReadULEB128(premature stream end)");
					}
					
					@value += ( (( bt & 127 )) << shift );
					if (( bt < 128 )) {
						break;
					}
					
					shift += 7;
				}
				
				return @value;
			}
		}
		
		
	}
}


