// Generated by Haxe 4.0.0+ef18b627e
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace openfl._internal.utils {
	public class ObjectPool : global::haxe.lang.HxObject {
		
		static bool __hx_init_called = false;
		static ObjectPool() {
			if(global::openfl._internal.utils.ObjectPool.__hx_init_called) return;
			global::openfl._internal.utils.ObjectPool.__hx_init_called = true;
			{
				#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				{
					#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					object __temp_odecl1 = new global::haxe.lang.DynamicObject(new int[]{13816588}, new object[]{new global::haxe.root.Array(new object[]{"checkstyle:FieldDocComment"})}, new int[]{}, new double[]{});
					#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					global::openfl._internal.utils.ObjectPool.__meta__ = new global::haxe.lang.DynamicObject(new int[]{5541879}, new object[]{__temp_odecl1}, new int[]{}, new double[]{});
				}
				
			}
			
		}
		#line default
		
		public ObjectPool(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public ObjectPool(global::haxe.lang.Function create, global::haxe.lang.Function clean, object size) {
			#line 19 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			global::openfl._internal.utils.ObjectPool.__hx_ctor_openfl__internal_utils_ObjectPool(((global::openfl._internal.utils.ObjectPool) (this) ), ((global::haxe.lang.Function) (create) ), ((global::haxe.lang.Function) (clean) ), ((object) (size) ));
		}
		#line default
		
		protected static void __hx_ctor_openfl__internal_utils_ObjectPool(global::openfl._internal.utils.ObjectPool __hx_this, global::haxe.lang.Function create, global::haxe.lang.Function clean, object size) {
			#line 68 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			__hx_this.create = new global::openfl._internal.utils.ObjectPool___hx_ctor_openfl__internal_utils_ObjectPool_68__Fun();
			#line 54 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			__hx_this.clean = new global::openfl._internal.utils.ObjectPool___hx_ctor_openfl__internal_utils_ObjectPool_54__Fun();
			#line 20 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			{
				#line 21 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				__hx_this.__pool = ((global::haxe.IMap) (new global::haxe.ds.ObjectMap()) );
				#line 23 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				__hx_this.activeObjects = 0;
				__hx_this.inactiveObjects = 0;
				#line 26 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				__hx_this.__inactiveObject0 = null;
				__hx_this.__inactiveObject1 = null;
				#line 28 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				__hx_this.__inactiveObjectList = new global::haxe.ds.List();
				#line 30 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				if (( create != null )) {
					#line 32 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					__hx_this.create = create;
				}
				
				#line 34 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				if (( clean != null )) {
					#line 36 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					__hx_this.clean = clean;
				}
				
				#line 38 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				if (( size != default(object) )) {
					#line 40 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					__hx_this.set_size(size);
				}
				
			}
			
		}
		#line default
		
		public static object __meta__;
		
		public int activeObjects;
		
		public int inactiveObjects;
		
		
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public object __inactiveObject0;
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public object __inactiveObject1;
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public global::haxe.ds.List __inactiveObjectList;
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public global::haxe.IMap __pool;
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public object __size;
		
		public virtual void @add(object @object) {
			#line 46 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			if ( ! (((global::haxe.IMap) (this.__pool) ).exists(@object)) ) {
				#line 48 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				((global::haxe.IMap) (this.__pool) ).@set(@object, false);
				this.clean.__hx_invoke1_o(default(double), @object);
				#line 50 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				{
					#line 50 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					if (global::haxe.lang.Runtime.eq(this.__inactiveObject0, null)) {
						#line 50 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__inactiveObject0 = @object;
					}
					else if (global::haxe.lang.Runtime.eq(this.__inactiveObject1, null)) {
						#line 50 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__inactiveObject1 = @object;
					}
					else {
						#line 50 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__inactiveObjectList.@add(@object);
					}
					
					#line 50 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					this.inactiveObjects++;
				}
				
			}
			
		}
		#line default
		
		public global::haxe.lang.Function clean;
		
		public virtual void clear() {
			#line 58 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			this.__pool = ((global::haxe.IMap) (new global::haxe.ds.ObjectMap()) );
			#line 60 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			this.activeObjects = 0;
			this.inactiveObjects = 0;
			#line 63 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			this.__inactiveObject0 = null;
			this.__inactiveObject1 = null;
			#line 65 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			this.__inactiveObjectList.clear();
		}
		#line default
		
		public global::haxe.lang.Function create;
		
		public virtual object @get() {
			#line 75 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			object @object = null;
			#line 77 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			if (( this.inactiveObjects > 0 )) {
				#line 79 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				object object1 = null;
				#line 79 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				if (( ! (global::haxe.lang.Runtime.eq(this.__inactiveObject0, null)) )) {
					#line 79 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					object1 = this.__inactiveObject0;
					#line 79 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					this.__inactiveObject0 = null;
				}
				else if (( ! (global::haxe.lang.Runtime.eq(this.__inactiveObject1, null)) )) {
					#line 79 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					object1 = this.__inactiveObject1;
					#line 79 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					this.__inactiveObject1 = null;
				}
				else {
					#line 79 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					object1 = this.__inactiveObjectList.pop();
					#line 79 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					if (( this.__inactiveObjectList.length > 0 )) {
						#line 79 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__inactiveObject0 = this.__inactiveObjectList.pop();
					}
					
					#line 79 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					if (( this.__inactiveObjectList.length > 0 )) {
						#line 79 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__inactiveObject1 = this.__inactiveObjectList.pop();
					}
					
				}
				
				#line 79 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				this.inactiveObjects--;
				#line 79 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				this.activeObjects++;
				#line 79 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				@object = ((object) (object1) );
			}
			else if (( ( this.__size == default(object) ) || ( this.activeObjects < ((int) (global::haxe.lang.Runtime.toInt(this.__size)) ) ) )) {
				#line 83 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				@object = ((object) (this.create.__hx_invoke0_o()) );
				#line 85 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				if (( ! (global::haxe.lang.Runtime.eq(@object, null)) )) {
					#line 87 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					((global::haxe.IMap) (this.__pool) ).@set(@object, true);
					this.activeObjects++;
				}
				
			}
			
			#line 92 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			return @object;
		}
		#line default
		
		public virtual void release(object @object) {
			#line 108 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			this.activeObjects--;
			#line 110 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			if (( ( this.__size == default(object) ) || ( ( this.activeObjects + this.inactiveObjects ) < ((int) (global::haxe.lang.Runtime.toInt(this.__size)) ) ) )) {
				#line 112 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				this.clean.__hx_invoke1_o(default(double), @object);
				{
					#line 113 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					if (global::haxe.lang.Runtime.eq(this.__inactiveObject0, null)) {
						#line 113 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__inactiveObject0 = @object;
					}
					else if (global::haxe.lang.Runtime.eq(this.__inactiveObject1, null)) {
						#line 113 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__inactiveObject1 = @object;
					}
					else {
						#line 113 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__inactiveObjectList.@add(@object);
					}
					
					#line 113 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					this.inactiveObjects++;
				}
				
			}
			else {
				#line 117 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				((global::haxe.IMap) (this.__pool) ).@remove(@object);
			}
			
		}
		#line default
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public void __addInactive(object @object) {
			#line 127 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			if (global::haxe.lang.Runtime.eq(this.__inactiveObject0, null)) {
				#line 129 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				this.__inactiveObject0 = @object;
			}
			else if (global::haxe.lang.Runtime.eq(this.__inactiveObject1, null)) {
				#line 133 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				this.__inactiveObject1 = @object;
			}
			else {
				#line 137 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				this.__inactiveObjectList.@add(@object);
			}
			
			#line 140 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			this.inactiveObjects++;
		}
		#line default
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public object __getInactive() {
			#line 145 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			object @object = null;
			#line 147 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			if (( ! (global::haxe.lang.Runtime.eq(this.__inactiveObject0, null)) )) {
				#line 149 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				@object = this.__inactiveObject0;
				this.__inactiveObject0 = null;
			}
			else if (( ! (global::haxe.lang.Runtime.eq(this.__inactiveObject1, null)) )) {
				#line 154 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				@object = this.__inactiveObject1;
				this.__inactiveObject1 = null;
			}
			else {
				#line 159 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				@object = this.__inactiveObjectList.pop();
				#line 161 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				if (( this.__inactiveObjectList.length > 0 )) {
					#line 163 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					this.__inactiveObject0 = this.__inactiveObjectList.pop();
				}
				
				#line 166 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				if (( this.__inactiveObjectList.length > 0 )) {
					#line 168 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					this.__inactiveObject1 = this.__inactiveObjectList.pop();
				}
				
			}
			
			#line 176 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			this.inactiveObjects--;
			this.activeObjects++;
			#line 179 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			return @object;
		}
		#line default
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void __removeInactive(int count) {
			#line 184 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			if (( ( count <= 0 ) || ( this.inactiveObjects == 0 ) )) {
				#line 184 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				return;
			}
			
			#line 186 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			if (( ! (global::haxe.lang.Runtime.eq(this.__inactiveObject0, null)) )) {
				#line 188 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				((global::haxe.IMap) (this.__pool) ).@remove(this.__inactiveObject0);
				this.__inactiveObject0 = null;
				#line 190 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				this.inactiveObjects--;
				 -- count;
			}
			
			#line 194 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			if (( ( count == 0 ) || ( this.inactiveObjects == 0 ) )) {
				#line 194 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				return;
			}
			
			#line 196 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			if (( ! (global::haxe.lang.Runtime.eq(this.__inactiveObject1, null)) )) {
				#line 198 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				((global::haxe.IMap) (this.__pool) ).@remove(this.__inactiveObject1);
				this.__inactiveObject1 = null;
				#line 200 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				this.inactiveObjects--;
				 -- count;
			}
			
			#line 204 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			if (( ( count == 0 ) || ( this.inactiveObjects == 0 ) )) {
				#line 204 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				return;
			}
			
			#line 206 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			{
				#line 206 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				global::haxe.ds._List.ListNode _g_head = this.__inactiveObjectList.h;
				#line 206 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				while (( _g_head != null )) {
					#line 206 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					object val = _g_head.item;
					#line 206 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					_g_head = _g_head.next;
					#line 206 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					object @object = ((object) (val) );
					#line 208 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					((global::haxe.IMap) (this.__pool) ).@remove(@object);
					this.__inactiveObjectList.@remove(@object);
					#line 210 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					this.inactiveObjects--;
					 -- count;
					#line 213 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					if (( ( count == 0 ) || ( this.inactiveObjects == 0 ) )) {
						#line 213 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return;
					}
					
				}
				
			}
			
		}
		#line default
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public virtual object get_size() {
			#line 220 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			return this.__size;
		}
		#line default
		
		[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
		public virtual object set_size(object @value) {
			#line 225 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			if (( @value == default(object) )) {
				#line 227 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				this.__size = null;
			}
			else {
				#line 231 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				int current = ( this.inactiveObjects + this.activeObjects );
				this.__size = @value;
				#line 234 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				if (( current > ((int) (global::haxe.lang.Runtime.toInt(@value)) ) )) {
					#line 236 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					this.__removeInactive(( ((int) (current) ) - ((int) (global::haxe.lang.Runtime.toInt(@value)) ) ));
				}
				else if (( ((int) (global::haxe.lang.Runtime.toInt(@value)) ) > current )) {
					#line 240 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					object @object = default(object);
					#line 242 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
					{
						#line 242 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						int _g = 0;
						#line 242 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						int _g1 = ( ((int) (global::haxe.lang.Runtime.toInt(@value)) ) - ((int) (current) ) );
						#line 242 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						while (( _g < _g1 )) {
							#line 242 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
							int i = _g++;
							#line 244 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
							@object = ((object) (this.create.__hx_invoke0_o()) );
							#line 246 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
							if (( ! (global::haxe.lang.Runtime.eq(@object, null)) )) {
								#line 248 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
								((global::haxe.IMap) (this.__pool) ).@set(@object, false);
								this.__inactiveObjectList.@add(@object);
								#line 250 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
								this.inactiveObjects++;
							}
							else {
								#line 254 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
								break;
							}
							
						}
						
					}
					
				}
				
			}
			
			#line 260 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			return @value;
		}
		#line default
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				switch (hash) {
					case 2068579297:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__size = ((object) (@value) );
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return @value;
					}
					
					
					case 2132884807:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__inactiveObject1 = ((object) (@value) );
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(((object) (@value) ))) );
					}
					
					
					case 2132884806:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__inactiveObject0 = ((object) (@value) );
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(((object) (@value) ))) );
					}
					
					
					case 1280549057:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.set_size(@value);
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return @value;
					}
					
					
					case 2076642473:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.inactiveObjects = ((int) (@value) );
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return @value;
					}
					
					
					case 974697390:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.activeObjects = ((int) (@value) );
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return @value;
					}
					
					
					default:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				switch (hash) {
					case 2081384188:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.create = ((global::haxe.lang.Function) (@value) );
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return @value;
					}
					
					
					case 1213952393:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.clean = ((global::haxe.lang.Function) (@value) );
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return @value;
					}
					
					
					case 2068579297:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__size = ((object) (@value) );
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return @value;
					}
					
					
					case 2035606524:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__pool = ((global::haxe.IMap) (@value) );
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return @value;
					}
					
					
					case 2124012840:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__inactiveObjectList = ((global::haxe.ds.List) (@value) );
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return @value;
					}
					
					
					case 2132884807:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__inactiveObject1 = ((object) (@value) );
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return @value;
					}
					
					
					case 2132884806:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__inactiveObject0 = ((object) (@value) );
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return @value;
					}
					
					
					case 1280549057:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.set_size(@value);
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return @value;
					}
					
					
					case 2076642473:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.inactiveObjects = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return @value;
					}
					
					
					case 974697390:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.activeObjects = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return @value;
					}
					
					
					default:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				switch (hash) {
					case 2053879230:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set_size", 2053879230)) );
					}
					
					
					case 1276009546:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_size", 1276009546)) );
					}
					
					
					case 1757798127:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "__removeInactive", 1757798127)) );
					}
					
					
					case 1486625537:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "__getInactive", 1486625537)) );
					}
					
					
					case 1678020492:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "__addInactive", 1678020492)) );
					}
					
					
					case 1491961287:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "release", 1491961287)) );
					}
					
					
					case 5144726:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get", 5144726)) );
					}
					
					
					case 2081384188:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return this.create;
					}
					
					
					case 1213952397:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "clear", 1213952397)) );
					}
					
					
					case 1213952393:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return this.clean;
					}
					
					
					case 4846113:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "add", 4846113)) );
					}
					
					
					case 2068579297:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return this.__size;
					}
					
					
					case 2035606524:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return this.__pool;
					}
					
					
					case 2124012840:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return this.__inactiveObjectList;
					}
					
					
					case 2132884807:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return this.__inactiveObject1;
					}
					
					
					case 2132884806:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return this.__inactiveObject0;
					}
					
					
					case 1280549057:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return this.get_size();
					}
					
					
					case 2076642473:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return this.inactiveObjects;
					}
					
					
					case 974697390:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return this.activeObjects;
					}
					
					
					default:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				switch (hash) {
					case 2068579297:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(this.__size)) );
					}
					
					
					case 2132884807:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(((object) (this.__inactiveObject1) ))) );
					}
					
					
					case 2132884806:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(((object) (this.__inactiveObject0) ))) );
					}
					
					
					case 1280549057:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((double) (global::haxe.lang.Runtime.toDouble(this.get_size())) );
					}
					
					
					case 2076642473:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((double) (this.inactiveObjects) );
					}
					
					
					case 974697390:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return ((double) (this.activeObjects) );
					}
					
					
					default:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				switch (hash) {
					case 2053879230:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return this.set_size(((object) (dynargs[0]) ));
					}
					
					
					case 1276009546:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return this.get_size();
					}
					
					
					case 1757798127:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__removeInactive(((int) (global::haxe.lang.Runtime.toInt(((object) (dynargs[0]) ))) ));
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						break;
					}
					
					
					case 1486625537:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return this.__getInactive();
					}
					
					
					case 1678020492:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.__addInactive(((object) (dynargs[0]) ));
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						break;
					}
					
					
					case 1491961287:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.release(((object) (dynargs[0]) ));
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						break;
					}
					
					
					case 5144726:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return this.@get();
					}
					
					
					case 1213952397:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.clear();
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						break;
					}
					
					
					case 4846113:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						this.@add(((object) (dynargs[0]) ));
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						break;
					}
					
					
					default:
					{
						#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::haxe.root.Array baseArr) {
			#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			baseArr.push("create");
			#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			baseArr.push("clean");
			#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			baseArr.push("__size");
			#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			baseArr.push("__pool");
			#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			baseArr.push("__inactiveObjectList");
			#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			baseArr.push("__inactiveObject1");
			#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			baseArr.push("__inactiveObject0");
			#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			baseArr.push("size");
			#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			baseArr.push("inactiveObjects");
			#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			baseArr.push("activeObjects");
			#line 7 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace openfl._internal.utils {
	public class ObjectPool___hx_ctor_openfl__internal_utils_ObjectPool_68__Fun : global::haxe.lang.Function {
		
		public ObjectPool___hx_ctor_openfl__internal_utils_ObjectPool_68__Fun() : base(0, 0) {
		}
		
		
		public override object __hx_invoke0_o() {
			#line 70 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			return null;
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace openfl._internal.utils {
	public class ObjectPool___hx_ctor_openfl__internal_utils_ObjectPool_54__Fun : global::haxe.lang.Function {
		
		public ObjectPool___hx_ctor_openfl__internal_utils_ObjectPool_54__Fun() : base(1, 0) {
		}
		
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 54 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			object @object = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((object) (__fn_float1) )) : (((object) (__fn_dyn1) )) );
			#line 54 "D:\\project\\sangong\\sangong\\src\\openfl\\_internal\\utils\\ObjectPool.hx"
			return null;
		}
		#line default
		
	}
}


