// Generated by Haxe 4.1.0-rc.1+0d88c583b
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace web.proto {
	public sealed class CMDEvent : global::openfl.events.Event {
		
		static CMDEvent() {
			global::web.proto.CMDEvent.EXCUTE = ((string) ("CMD_excute") );
			global::web.proto.CMDEvent.RESULT = ((string) ("CMD_result") );
		}
		
		
		public CMDEvent(global::haxe.lang.EmptyObject empty) : base(global::haxe.lang.EmptyObject.EMPTY) {
		}
		
		
		public CMDEvent(string type, object cmd, global::server.IHander hander, object bubbles, object cancelable) : base(global::haxe.lang.EmptyObject.EMPTY) {
			global::web.proto.CMDEvent.__hx_ctor_web_proto_CMDEvent(this, type, cmd, hander, bubbles, cancelable);
		}
		
		
		private static void __hx_ctor_web_proto_CMDEvent(global::web.proto.CMDEvent __hx_this, string type, object cmd, global::server.IHander hander, object bubbles, object cancelable) {
			bool cancelable1 = ( (( cancelable == default(object) )) ? (false) : (global::haxe.lang.Runtime.toBool(cancelable)) );
			bool bubbles1 = ( (( bubbles == default(object) )) ? (true) : (global::haxe.lang.Runtime.toBool(bubbles)) );
			global::openfl.events.Event.__hx_ctor_openfl_events_Event(__hx_this, type, bubbles1, cancelable1);
			__hx_this.cmd = cmd;
			__hx_this.hander = hander;
		}
		
		
		public static string EXCUTE;
		
		public static string RESULT;
		
		public object cmd;
		
		public global::server.IHander hander;
		
		public override global::openfl.events.Event clone() {
			global::web.proto.CMDEvent @event = new global::web.proto.CMDEvent(this.type, this.cmd, this.hander, this.bubbles, this.cancelable);
			@event.target = this.target;
			@event.currentTarget = this.currentTarget;
			@event.eventPhase = this.eventPhase;
			@event.hander = this.hander;
			return @event;
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 4947578:
					{
						this.cmd = ((object) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 939359644:
					{
						this.hander = ((global::server.IHander) (@value) );
						return @value;
					}
					
					
					case 4947578:
					{
						this.cmd = ((object) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1214452573:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "clone", 1214452573)) );
					}
					
					
					case 939359644:
					{
						return this.hander;
					}
					
					
					case 4947578:
					{
						return this.cmd;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 4947578:
					{
						return ((double) (global::haxe.lang.Runtime.toDouble(this.cmd)) );
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::haxe.root.Array baseArr) {
			baseArr.push("hander");
			baseArr.push("cmd");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


