// Generated by Haxe 4.1.0-rc.1+0d88c583b

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hx.ws._BinaryType {
	public sealed class BinaryType_Impl_ {
		
		static BinaryType_Impl_() {
			#line 10 "D:\\project\\sangong\\sangong\\src\\hx\\ws\\BinaryType.hx"
			global::hx.ws._BinaryType.BinaryType_Impl_.ARRAYBUFFER = ((string) ("arraybuffer") );
		}
		#line default
		
		public static string ARRAYBUFFER;
		
		public static string toString(string this1) {
			#line 13 "D:\\project\\sangong\\sangong\\src\\hx\\ws\\BinaryType.hx"
			return this1;
		}
		#line default
		
	}
}


