// Generated by Haxe 4.1.0-rc.1+0d88c583b
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hx.ws {
	public class HttpHeader : global::haxe.lang.HxObject {
		
		static HttpHeader() {
			global::hx.ws.HttpHeader.SEC_WEBSOCKET_KEY = "Sec-WebSocket-Key";
			global::hx.ws.HttpHeader.SEC_WEBSOSCKET_ACCEPT = "Sec-WebSocket-Accept";
			global::hx.ws.HttpHeader.SEC_WEBSOSCKET_VERSION = "Sec-WebSocket-Version";
			global::hx.ws.HttpHeader.UPGRADE = "Upgrade";
			global::hx.ws.HttpHeader.HOST = "Host";
			global::hx.ws.HttpHeader.CONNECTION = "Connection";
			global::hx.ws.HttpHeader.USER_AGENT = "User-Agent";
			global::hx.ws.HttpHeader.PRAGMA = "Pragma";
			global::hx.ws.HttpHeader.CACHE_CONTROL = "Cache-Control";
			global::hx.ws.HttpHeader.ORIGIN = "Origin";
			global::hx.ws.HttpHeader.X_WEBSOCKET_REJECT_REASON = "X-WebSocket-Reject-Reason";
		}
		
		
		public HttpHeader(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public HttpHeader() {
			global::hx.ws.HttpHeader.__hx_ctor_hx_ws_HttpHeader(this);
		}
		
		
		protected static void __hx_ctor_hx_ws_HttpHeader(global::hx.ws.HttpHeader __hx_this) {
		}
		
		
		public static string SEC_WEBSOCKET_KEY;
		
		public static string SEC_WEBSOSCKET_ACCEPT;
		
		public static string SEC_WEBSOSCKET_VERSION;
		
		public static string UPGRADE;
		
		public static string HOST;
		
		public static string CONNECTION;
		
		public static string USER_AGENT;
		
		public static string PRAGMA;
		
		public static string CACHE_CONTROL;
		
		public static string ORIGIN;
		
		public static string X_WEBSOCKET_REJECT_REASON;
		
	}
}


