// Generated by Haxe 4.0.2+606b176a3

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hx.ws._OpCode {
	public sealed class OpCode_Impl_ {
		
		static OpCode_Impl_() {
			unchecked{
				#line 4 "C:\\projects\\BCGAME\\sangong\\src\\hx\\ws\\OpCode.hx"
				global::hx.ws._OpCode.OpCode_Impl_.Continuation = ((int) (0) );
				global::hx.ws._OpCode.OpCode_Impl_.Text = ((int) (1) );
				#line 6 "C:\\projects\\BCGAME\\sangong\\src\\hx\\ws\\OpCode.hx"
				global::hx.ws._OpCode.OpCode_Impl_.Binary = ((int) (2) );
				global::hx.ws._OpCode.OpCode_Impl_.Close = ((int) (8) );
				#line 8 "C:\\projects\\BCGAME\\sangong\\src\\hx\\ws\\OpCode.hx"
				global::hx.ws._OpCode.OpCode_Impl_.Ping = ((int) (9) );
				global::hx.ws._OpCode.OpCode_Impl_.Pong = ((int) (10) );
			}
		}
		#line default
		
		public static int Continuation;
		
		public static int Text;
		
		public static int Binary;
		
		public static int Close;
		
		public static int Ping;
		
		public static int Pong;
		
		public static int toInt(int this1) {
			#line 12 "C:\\projects\\BCGAME\\sangong\\src\\hx\\ws\\OpCode.hx"
			return this1;
		}
		#line default
		
	}
}


