// Generated by Haxe 4.1.0-rc.1+0d88c583b
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace hx.ws {
	public class Utf8Encoder : global::haxe.lang.HxObject {
		
		public Utf8Encoder(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Utf8Encoder() {
			global::hx.ws.Utf8Encoder.__hx_ctor_hx_ws_Utf8Encoder(this);
		}
		
		
		protected static void __hx_ctor_hx_ws_Utf8Encoder(global::hx.ws.Utf8Encoder __hx_this) {
		}
		
		
		public static global::haxe.io.Bytes encode(string str) {
			return global::haxe.io.Bytes.ofString(str, null);
		}
		
		
		public static string decode(global::haxe.io.Bytes data) {
			return data.toString();
		}
		
		
	}
}


