// Generated by Haxe 4.0.0+ef18b627e

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace openfl.events._EventType {
	public sealed class EventType_Impl_ {
		
		public static bool @equals<T>(string a, string b) {
			#line 21 "D:\\project\\sangong\\sangong\\src\\openfl\\events\\EventType.hx"
			return ( ((string) (a) ) == b );
		}
		#line default
		
		public static bool notEquals<T>(string a, string b) {
			#line 26 "D:\\project\\sangong\\sangong\\src\\openfl\\events\\EventType.hx"
			return ( ((string) (a) ) != b );
		}
		#line default
		
	}
}


