// Generated by Haxe 4.0.2+606b176a3
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace openfl.events {
	public interface IEventDispatcher : global::haxe.lang.IHxObject {
		
		void addEventListener(string type, global::haxe.lang.Function listener, object useCapture, object priority, object useWeakReference);
		
		bool dispatchEvent(global::openfl.events.Event @event);
		
		bool hasEventListener(string type);
		
		void removeEventListener(string type, global::haxe.lang.Function listener, object useCapture);
		
		bool willTrigger(string type);
		
	}
}


