// Generated by Haxe 4.1.0-rc.1+0d88c583b

using haxe.root;
using Newtonsoft.Json;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace web
{
    public class TinyBilingCS
    {
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public int playerID;
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public int bling;
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public int roomID;
    }
}