// Generated by Haxe 4.1.0-rc.1+0d88c583b

using Newtonsoft.Json;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace web {
	public struct TinyCMDCS {


        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public int cmd;
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public object @value;
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public int id;
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public string password;
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public string openid;
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public object[] players;
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public object player;
		
	}
}


