// Generated by Haxe 4.1.0-rc.1+0d88c583b

using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace web
{
    public class TinyBilingCS
    {
        public int playerID;
        public int bling;
        public int roomID;
    }
}